/**
 * Extends from names.tsx by associating to CHARACTERS enum to relevant data.
 */

import { ELEMENTS } from "../elements";
import { GenericDetails } from "../generic";
import { RARITY } from "../rarity";
import { WEAPONS } from "../weapons";
import { CHARACTERS } from "./names";

export type CharacterMap = {
	[index in CHARACTERS]: CharacterDetail;
};

export interface CharacterDetail extends GenericDetails {
	element: ELEMENTS;
	weapon: WEAPONS;
	rarity: RARITY;
	index: Number;
}

export const CHARACTER_INFO: CharacterMap = {
	[CHARACTERS.NoBan]: {
		displayName: "No Ban",
		element: ELEMENTS.physical,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "NoBan",
		onlineFilePath: "https://thumbs4.imagebam.com/4b/77/61/METSLWN_t.png",
		index: -2,
	},
	[CHARACTERS.None]: {
		displayName: "None",
		element: ELEMENTS.physical,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "NoBan",
		onlineFilePath: "https://thumbs4.imagebam.com/4b/77/61/METSLWN_t.png",
		index: -1,
	},
	[CHARACTERS.Albedo]: {
		displayName: "Albedo",
		element: ELEMENTS.geo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Albedo",
		onlineFilePath: "https://thumbs4.imagebam.com/94/cb/3f/METQJBR_t.png",
		index: 26,
	},
	[CHARACTERS.Alhaitham]: {
		displayName: "Alhaitham",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Alhaitham",
		onlineFilePath: "https://thumbs4.imagebam.com/57/5e/59/METQJBT_t.png",
		index: 61,
	},
	[CHARACTERS.Aloy]: {
		displayName: "Aloy",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Aloy",
		onlineFilePath: "https://thumbs4.imagebam.com/91/7c/0d/METQJBQ_t.png",
		index: 37,
	},
	[CHARACTERS.Amber]: {
		displayName: "Amber",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Amber",
		onlineFilePath: "https://thumbs4.imagebam.com/a8/dc/96/METQJBO_t.png",
		index: 0,
	},
	[CHARACTERS.Arlecchino]: {
		displayName: "Arlecchino",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Arlecchino",
		onlineFilePath: "https://thumbs4.imagebam.com/8a/96/d0/METQJDD_t.png",
		index: 80,
	},
	[CHARACTERS.Ayaka]: {
		displayName: "Ayaka",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Ayaka",
		onlineFilePath: "https://thumbs4.imagebam.com/05/d0/e7/METQJBW_t.png",
		index: 34,
	},
	[CHARACTERS.Ayato]: {
		displayName: "Ayato",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Ayato",
		onlineFilePath: "https://thumbs4.imagebam.com/21/c4/cb/METQJBU_t.png",
		index: 47,
	},
	[CHARACTERS.Baizhu]: {
		displayName: "Baizhu",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Baizhu",
		onlineFilePath: "https://thumbs4.imagebam.com/b7/3a/ef/METQJBJ_t.png",
		index: 65,
	},
	[CHARACTERS.Barbara]: {
		displayName: "Barbara",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Barbara",
		onlineFilePath: "https://images4.imagebam.com/33/00/cb/METQJBM_o.png",
		index: 1,
	},
	[CHARACTERS.Beidou]: {
		displayName: "Beidou",
		element: ELEMENTS.electro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Beidou",
		onlineFilePath: "https://images4.imagebam.com/68/e6/47/METQJBL_o.png",
		index: 2,
	},
	[CHARACTERS.Bennett]: {
		displayName: "Bennett",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Bennett",
		onlineFilePath: "https://images4.imagebam.com/c3/a6/cb/METQJBK_o.png",
		index: 3,
	},
	[CHARACTERS.Candace]: {
		displayName: "Candace",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Candace",
		onlineFilePath: "https://thumbs4.imagebam.com/6a/8e/08/METQJBI_t.png",
		index: 54,
	},
	[CHARACTERS.Charlotte]: {
		displayName: "Charlotte",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Charlotte",
		onlineFilePath: "https://thumbs4.imagebam.com/3e/39/8a/METQJBD_t.png",
		index: 73,
	},
	[CHARACTERS.Chevreuse]: {
		displayName: "Chevreuse",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Chevreuse",
		onlineFilePath: "https://thumbs4.imagebam.com/ed/35/9e/METS0VO_t.png",
		index: 75,
	},
	[CHARACTERS.Chiori]: {
		displayName: "Chiori",
		element: ELEMENTS.geo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Chiori",
		onlineFilePath: "https://thumbs4.imagebam.com/de/01/04/METS0VN_t.png",
		index: 79,
	},
	[CHARACTERS.Chasca]: {
		displayName: "Chasca",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Chasca",
		onlineFilePath: "https://thumbs4.imagebam.com/19/28/0e/MEWPYV1_t.png",
		index: 89,
	},
	[CHARACTERS.Chongyun]: {
		displayName: "Chongyun",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Chongyun",
		onlineFilePath: "https://thumbs4.imagebam.com/90/f5/2a/METQJBG_t.png",
		index: 4,
	},
	[CHARACTERS.Clorinde]: {
		displayName: "Clorinde",
		element: ELEMENTS.electro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Clorinde",
		onlineFilePath: "https://images4.imagebam.com/41/11/8c/MEUJVCR_o.png",
		index: 81,
	},
	[CHARACTERS.Collei]: {
		displayName: "Collei",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Collei",
		onlineFilePath: "https://thumbs4.imagebam.com/16/31/d8/METQJBE_t.png",
		index: 51,
	},
	[CHARACTERS.Cyno]: {
		displayName: "Cyno",
		element: ELEMENTS.electro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Cyno",
		onlineFilePath: "https://thumbs4.imagebam.com/f9/45/66/METQJB6_t.png",
		index: 55,
	},
	[CHARACTERS.Dehya]: {
		displayName: "Dehya",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "Dehya",
		onlineFilePath: "https://thumbs4.imagebam.com/e6/0c/7f/METQJBB_t.png",
		index: 63,
	},
	[CHARACTERS.Diluc]: {
		displayName: "Diluc",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "Diluc",
		onlineFilePath: "https://thumbs4.imagebam.com/4c/a5/b0/METQJB9_t.png",
		index: 5,
	},
	[CHARACTERS.Diona]: {
		displayName: "Diona",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Diona",
		onlineFilePath: "https://thumbs4.imagebam.com/2e/90/08/METQJB8_t.png",
		index: 22,
	},
	[CHARACTERS.Dori]: {
		displayName: "Dori",
		element: ELEMENTS.electro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Dori",
		onlineFilePath: "https://thumbs4.imagebam.com/0c/c1/f4/METQJAC_t.png",
		index: 52,
	},
	[CHARACTERS.Emilie]: {
		displayName: "Emilie",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Emilie",
		onlineFilePath: "https://thumbs4.imagebam.com/a8/c7/23/MEV7JII_t.png",
		index: 84,
	},
	[CHARACTERS.Eula]: {
		displayName: "Eula",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "Eula",
		onlineFilePath: "https://thumbs4.imagebam.com/0e/dd/42/METQJB4_t.png",
		index: 31,
	},
	[CHARACTERS.Faruzan]: {
		displayName: "Faruzan",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Faruzan",
		onlineFilePath: "https://thumbs4.imagebam.com/ed/0f/2f/METQJB2_t.png",
		index: 59,
	},
	[CHARACTERS.Fischl]: {
		displayName: "Fischl",
		element: ELEMENTS.electro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Fischl",
		onlineFilePath: "https://thumbs4.imagebam.com/70/64/fd/METQJAY_t.png",
		index: 6,
	},
	[CHARACTERS.Freminet]: {
		displayName: "Freminet",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Freminet",
		onlineFilePath: "https://thumbs4.imagebam.com/8d/e1/0a/METQJAZ_t.png",
		index: 68,
	},
	[CHARACTERS.Furina]: {
		displayName: "Furina",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Furina",
		onlineFilePath: "https://thumbs4.imagebam.com/a2/cd/6f/METQJAU_t.png",
		index: 74,
	},
	[CHARACTERS.Gaming]: {
		displayName: "Gaming",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Gaming",
		onlineFilePath: "https://thumbs4.imagebam.com/81/d2/b6/METQJD8_t.png",
		index: 77,
	},
	[CHARACTERS.Ganyu]: {
		displayName: "Ganyu",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Ganyu",
		onlineFilePath: "https://thumbs4.imagebam.com/5e/dc/50/METQJAW_t.png",
		index: 27,
	},
	[CHARACTERS.Gorou]: {
		displayName: "Gorou",
		element: ELEMENTS.geo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Gorou",
		onlineFilePath: "https://thumbs4.imagebam.com/27/84/eb/METQJAT_t.png",
		index: 43,
	},
	[CHARACTERS.HuTao]: {
		displayName: "Hu Tao",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "HuTao",
		onlineFilePath: "https://thumbs4.imagebam.com/80/09/f3/METQJAJ_t.png",
		index: 28,
	},
	[CHARACTERS.Itto]: {
		displayName: "Itto",
		element: ELEMENTS.geo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "Itto",
		onlineFilePath: "https://thumbs4.imagebam.com/f9/1e/15/METQJAG_t.png",
		index: 42,
	},
	[CHARACTERS.Jean]: {
		displayName: "Jean",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Jean",
		onlineFilePath: "https://thumbs4.imagebam.com/a0/73/98/METRZ3L_t.png",
		index: 7,
	},
	[CHARACTERS.Kachina]: {
		displayName: "Kachina",
		element: ELEMENTS.geo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Kachina",
		onlineFilePath: "https://images4.imagebam.com/56/5d/d4/MEVNLM6_o.png",
		index: 85,
	},
	[CHARACTERS.Kaeya]: {
		displayName: "Kaeya",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Kaeya",
		onlineFilePath: "https://thumbs4.imagebam.com/75/bc/ba/METQJAF_t.png",
		index: 8,
	},
	[CHARACTERS.Kaveh]: {
		displayName: "Kaveh",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Kaveh",
		onlineFilePath: "https://thumbs4.imagebam.com/71/36/6c/METQJAD_t.png",
		index: 66,
	},
	[CHARACTERS.Kazuha]: {
		displayName: "Kazuha",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Kazuha",
		onlineFilePath: "https://thumbs4.imagebam.com/d2/48/34/METQJAS_t.png",
		index: 33,
	},
	[CHARACTERS.Keqing]: {
		displayName: "Keqing",
		element: ELEMENTS.electro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Keqing",
		onlineFilePath: "https://thumbs4.imagebam.com/13/18/96/METQJAR_t.png",
		index: 9,
	},
	[CHARACTERS.Kinich]: {
		displayName: "Kinich",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "Kinich",
		onlineFilePath: "https://thumbs4.imagebam.com/83/2f/e8/MEVP9X3_t.png",
		index: 86,
	},
	[CHARACTERS.Kirara]: {
		displayName: "Kirara",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Kirara",
		onlineFilePath: "https://thumbs4.imagebam.com/73/52/07/METQJC1_t.png",
		index: 67,
	},
	[CHARACTERS.Klee]: {
		displayName: "Klee",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Klee",
		onlineFilePath: "https://thumbs4.imagebam.com/04/1e/c0/METQJAL_t.png",
		index: 10,
	},
	[CHARACTERS.KujouSara]: {
		displayName: "Kujou Sara",
		element: ELEMENTS.electro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "KujouSara",
		onlineFilePath: "https://thumbs4.imagebam.com/76/9f/7a/METQJCG_t.png",
		index: 38,
	},
	[CHARACTERS.KukiShinobu]: {
		displayName: "Kuki Shinobu",
		element: ELEMENTS.electro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "KukiShinobu",
		onlineFilePath: "https://thumbs4.imagebam.com/0b/62/de/METQJCI_t.png",
		index: 48,
	},
	[CHARACTERS.Layla]: {
		displayName: "Layla",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Layla",
		onlineFilePath: "https://thumbs4.imagebam.com/ab/67/dd/METQJAO_t.png",
		index: 57,
	},
	[CHARACTERS.Lisa]: {
		displayName: "Lisa",
		element: ELEMENTS.electro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Lisa",
		onlineFilePath: "https://thumbs4.imagebam.com/49/c8/75/METS28H_t.png",
		index: 11,
	},
	[CHARACTERS.Lynette]: {
		displayName: "Lynette",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Lynette",
		onlineFilePath: "https://thumbs4.imagebam.com/91/96/5f/METQJBY_t.png",
		index: 69,
	},
	[CHARACTERS.Lyney]: {
		displayName: "Lyney",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Lyney",
		onlineFilePath: "https://thumbs4.imagebam.com/f3/c0/c6/METQJAK_t.png",
		index: 70,
	},
	[CHARACTERS.Mualani]: {
		displayName: "Mualani",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Mualani",
		onlineFilePath: "https://images4.imagebam.com/0a/a1/d5/MEVNRM0_o.png",
		index: 87,
	},
	[CHARACTERS.Mika]: {
		displayName: "Mika",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Mika",
		onlineFilePath: "https://thumbs4.imagebam.com/7d/f5/56/METQJBX_t.png",
		index: 64,
	},
	[CHARACTERS.Mona]: {
		displayName: "Mona",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Mona",
		onlineFilePath: "https://thumbs4.imagebam.com/75/44/9d/MEWLE3H_t.png",
		index: 12,
	},
	[CHARACTERS.Nahida]: {
		displayName: "Nahida",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Nahida",
		onlineFilePath: "https://thumbs4.imagebam.com/f0/62/cf/METQJC3_t.png",
		index: 58,
	},
	[CHARACTERS.Navia]: {
		displayName: "Navia",
		element: ELEMENTS.geo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "Navia",
		onlineFilePath: "https://thumbs4.imagebam.com/0b/cf/1f/METS0VM_t.png",
		index: 76,
	},
	[CHARACTERS.Neuvillette]: {
		displayName: "Neuvillette",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Neuvillette",
		onlineFilePath: "https://thumbs4.imagebam.com/92/5c/63/METQJC4_t.png",
		index: 71,
	},
	[CHARACTERS.Nilou]: {
		displayName: "Nilou",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Nilou",
		onlineFilePath: "https://thumbs4.imagebam.com/ef/72/d5/METQJC5_t.png",
		index: 56,
	},
	[CHARACTERS.Ningguang]: {
		displayName: "Ningguang",
		element: ELEMENTS.geo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Ningguang",
		onlineFilePath: "https://thumbs4.imagebam.com/b7/0f/c8/METQJC7_t.png",
		index: 13,
	},
	[CHARACTERS.Noelle]: {
		displayName: "Noelle",
		element: ELEMENTS.geo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Noelle",
		onlineFilePath: "https://thumbs4.imagebam.com/a8/73/55/METQJC9_t.png",
		index: 14,
	},
	[CHARACTERS.Ororon]: {
		displayName: "Ororon",
		element: ELEMENTS.electro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Ororon",
		onlineFilePath: "https://thumbs4.imagebam.com/15/47/b5/MEWPYV3_t.png",
		index: 90,
	},
	[CHARACTERS.Qiqi]: {
		displayName: "Qiqi",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Qiqi",
		onlineFilePath: "https://thumbs4.imagebam.com/42/9d/6a/METQJCB_t.png",
		index: 15,
	},
	[CHARACTERS.Raiden]: {
		displayName: "Raiden",
		element: ELEMENTS.electro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Raiden",
		onlineFilePath: "https://thumbs4.imagebam.com/22/94/bb/METQJCK_t.png",
		index: 39,
	},
	[CHARACTERS.Razor]: {
		displayName: "Razor",
		element: ELEMENTS.electro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Razor",
		onlineFilePath: "https://thumbs4.imagebam.com/5b/8b/0e/METQJCC_t.png",
		index: 16,
	},
	[CHARACTERS.Rosaria]: {
		displayName: "Rosaria",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Rosaria",
		onlineFilePath: "https://thumbs4.imagebam.com/e9/82/bb/METQJCF_t.png",
		index: 30,
	},
	[CHARACTERS.Kokomi]: {
		displayName: "Kokomi",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Kokomi",
		onlineFilePath: "https://thumbs4.imagebam.com/a3/7d/16/METQJAP_t.png",
		index: 40,
	},
	[CHARACTERS.Sayu]: {
		displayName: "Sayu",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Sayu",
		onlineFilePath: "https://thumbs4.imagebam.com/97/8b/17/METQJCH_t.png",
		index: 35,
	},
	[CHARACTERS.Sethos]: {
		displayName: "Sethos",
		element: ELEMENTS.electro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Sethos",
		onlineFilePath: "https://thumbs4.imagebam.com/84/f2/7e/MEU01T3_t.png",
		index: 82,
	},
	[CHARACTERS.Shenhe]: {
		displayName: "Shenhe",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Shenhe",
		onlineFilePath: "https://thumbs4.imagebam.com/ec/bc/52/METS0IA_t.png",
		index: 44,
	},
	[CHARACTERS.Heizou]: {
		displayName: "Heizou",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Heizou",
		onlineFilePath: "https://thumbs4.imagebam.com/f2/21/06/METQJAI_t.png",
		index: 50,
	},
	[CHARACTERS.Sigewinne]: {
		displayName: "Sigewinne",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Sigewinne",
		onlineFilePath: "https://thumbs4.imagebam.com/f3/c8/ec/MEU3RBW_t.png",
		index: 83,
	},
	[CHARACTERS.Sucrose]: {
		displayName: "Sucrose",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Sucrose",
		onlineFilePath: "https://thumbs4.imagebam.com/ef/40/e5/METQJCM_t.png",
		index: 17,
	},
	[CHARACTERS.Tartaglia]: {
		displayName: "Tartaglia",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Tartaglia",
		onlineFilePath: "https://thumbs4.imagebam.com/05/fb/5c/METQJCN_t.png",
		index: 23,
	},
	[CHARACTERS.Thoma]: {
		displayName: "Thoma",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Thoma",
		onlineFilePath: "https://thumbs4.imagebam.com/24/62/90/METQJCS_t.png",
		index: 41,
	},
	[CHARACTERS.Tighnari]: {
		displayName: "Tighnari",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Tighnari",
		onlineFilePath: "https://thumbs4.imagebam.com/e8/6f/ba/METQJCP_t.png",
		index: 53,
	},
	[CHARACTERS.Traveler]: {
		displayName: "Traveler",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Traveler",
		onlineFilePath: "https://thumbs4.imagebam.com/da/bf/b3/METS289_t.png",
		index: 18,
	},
	[CHARACTERS.Venti]: {
		displayName: "Venti",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Venti",
		onlineFilePath: "https://thumbs4.imagebam.com/f1/cd/6b/METQJCO_t.png",
		index: 19,
	},
	[CHARACTERS.Wanderer]: {
		displayName: "Wanderer",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Wanderer",
		onlineFilePath: "https://thumbs4.imagebam.com/bc/51/34/METQJCT_t.png",
		index: 60,
	},
	[CHARACTERS.Wriothesley]: {
		displayName: "Wriothesley",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Wriothesley",
		onlineFilePath: "https://thumbs4.imagebam.com/d4/f9/d7/METQJCW_t.png",
		index: 72,
	},
	[CHARACTERS.Xiangling]: {
		displayName: "Xiangling",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Xiangling",
		onlineFilePath: "https://thumbs4.imagebam.com/08/18/10/METQJCU_t.png",
		index: 20,
	},
	[CHARACTERS.Xianyun]: {
		displayName: "Xianyun",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Xianyun",
		onlineFilePath: "https://thumbs4.imagebam.com/a0/45/ef/METQJDB_t.png",
		index: 78,
	},
	[CHARACTERS.Xiao]: {
		displayName: "Xiao",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Xiao",
		onlineFilePath: "https://thumbs4.imagebam.com/e9/66/fc/METQJCX_t.png",
		index: 29,
	},
	[CHARACTERS.Xilonen]: {
		displayName: "Xilonen",
		element: ELEMENTS.geo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Xilonen",
		onlineFilePath: "https://thumbs4.imagebam.com/d5/26/5e/MEWLE3G_t.png",
		index: 88,
	},
	[CHARACTERS.Xingqiu]: {
		displayName: "Xingqiu",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Xingqiu",
		onlineFilePath: "https://thumbs4.imagebam.com/a2/d4/57/METRZQ9_t.png",
		index: 21,
	},
	[CHARACTERS.Xinyan]: {
		displayName: "Xinyan",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Xinyan",
		onlineFilePath: "https://thumbs4.imagebam.com/1d/c6/db/METQJD1_t.png",
		index: 24,
	},
	[CHARACTERS.YaeMiko]: {
		displayName: "Yae Miko",
		element: ELEMENTS.electro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "YaeMiko",
		onlineFilePath: "https://thumbs4.imagebam.com/04/67/d4/METQJCZ_t.png",
		index: 46,
	},
	[CHARACTERS.Yanfei]: {
		displayName: "Yanfei",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Yanfei",
		onlineFilePath: "https://thumbs4.imagebam.com/e5/f9/6a/METQJB1_t.png",
		index: 32,
	},
	[CHARACTERS.Yaoyao]: {
		displayName: "Yaoyao",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Yaoyao",
		onlineFilePath: "https://thumbs4.imagebam.com/92/84/cc/METQJD3_t.png",
		index: 62,
	},
	[CHARACTERS.Yelan]: {
		displayName: "Yelan",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Yelan",
		onlineFilePath: "https://thumbs4.imagebam.com/6d/cd/fb/METQJD4_t.png",
		index: 49,
	},
	[CHARACTERS.Yoimiya]: {
		displayName: "Yoimiya",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Yoimiya",
		onlineFilePath: "https://thumbs4.imagebam.com/30/06/d0/METQJD5_t.png",
		index: 36,
	},
	[CHARACTERS.YunJin]: {
		displayName: "Yun Jin",
		element: ELEMENTS.geo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "YunJin",
		onlineFilePath: "https://thumbs4.imagebam.com/2e/c7/ac/METQJD6_t.png",
		index: 45,
	},
	[CHARACTERS.Zhongli]: {
		displayName: "Zhongli",
		element: ELEMENTS.geo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Zhongli",
		onlineFilePath: "https://thumbs4.imagebam.com/37/16/5c/METQJD7_t.png",
		index: 25,
	},
};
