/**
 * Extends from names.tsx by associating to CHARACTERS enum to relevant data.
 */

import { ELEMENTS } from "../elements";
import { GenericDetails } from "../generic";
import { RARITY } from "../rarity";
import { WEAPONS } from "../weapons";
import { CHARACTERS } from "./names";

export type CharacterMap = {
	[index in CHARACTERS]: CharacterDetail;
};

export interface CharacterDetail extends GenericDetails {
	element: ELEMENTS;
	weapon: WEAPONS;
	rarity: RARITY;
	index: Number;
}

export const CHARACTER_INFO: CharacterMap = {
	[CHARACTERS.Albedo]: {
		displayName: "Albedo",
		element: ELEMENTS.geo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Albedo",
		index: 26,
	},
	[CHARACTERS.Alhaitham]: {
		displayName: "Alhaitham",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Alhaitham",
		index: 61,
	},
	[CHARACTERS.Aloy]: {
		displayName: "Aloy",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Aloy",
		index: 37,
	},
	[CHARACTERS.Amber]: {
		displayName: "Amber",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Amber",
		index: 0,
	},
	[CHARACTERS.AratakiItto]: {
		displayName: "Itto",
		element: ELEMENTS.geo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "AratakiItto",
		index: 42,
	},
	[CHARACTERS.Arlecchino]: {
		displayName: "Arlecchino",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Arlecchino",
		index: 80,
	},
	[CHARACTERS.Baizhu]: {
		displayName: "Baizhu",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Baizhu",
		index: 65,
	},
	[CHARACTERS.Barbara]: {
		displayName: "Barbara",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Barbara",
		index: 1,
	},
	[CHARACTERS.Beidou]: {
		displayName: "Beidou",
		element: ELEMENTS.electro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Beidou",
		index: 2,
	},
	[CHARACTERS.Bennett]: {
		displayName: "Bennett",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Bennett",
		index: 3,
	},
	[CHARACTERS.Candace]: {
		displayName: "Candace",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Candace",
		index: 54,
	},
	[CHARACTERS.Charlotte]: {
		displayName: "Charlotte",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Charlotte",
		index: 73
	},
	[CHARACTERS.Chevreuse]: {
		displayName: "Chevreuse",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Chevreuse",
		index: 75,
	},
	[CHARACTERS.Chiori]: {
		displayName: "Chiori",
		element: ELEMENTS.geo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Chiori",
		index: 79,
	},
	[CHARACTERS.Chongyun]: {
		displayName: "Chongyun",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Chongyun",
		index: 4,
	},
	[CHARACTERS.Clorinde]: {
		displayName: "Clorinde",
		element: ELEMENTS.electro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Clorinde",
		index: 81,
	},
	[CHARACTERS.Collei]: {
		displayName: "Collei",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Collei",
		index: 51,
	},
	[CHARACTERS.Cyno]: {
		displayName: "Cyno",
		element: ELEMENTS.electro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Cyno",
		index: 55,
	},
	[CHARACTERS.Dehya]: {
		displayName: "Dehya",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "Dehya",
		index: 63,
	},
	[CHARACTERS.Diluc]: {
		displayName: "Diluc",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "Diluc",
		index: 5,
	},
	[CHARACTERS.Diona]: {
		displayName: "Diona",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Diona",
		index: 22,
	},
	[CHARACTERS.Dori]: {
		displayName: "Dori",
		element: ELEMENTS.electro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Dori",
		index: 52,
	},
	[CHARACTERS.Emilie]: {
		displayName: "Emilie",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Emilie",
		index: 84
	},
	[CHARACTERS.Eula]: {
		displayName: "Eula",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "Eula",
		index: 31,
	},
	[CHARACTERS.Faruzan]: {
		displayName: "Faruzan",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Faruzan",
		index: 59,
	},
	[CHARACTERS.Fischl]: {
		displayName: "Fischl",
		element: ELEMENTS.electro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Fischl",
		index: 6
	},
	[CHARACTERS.Freminet]: {
		displayName: "Freminet",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Freminet",
		index: 68,
	},
	[CHARACTERS.Furina]: {
		displayName: "Furina",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Furina",
		index: 74,
	},
	[CHARACTERS.Gaming]: {
		displayName: "Gaming",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Gaming",
		index: 77,
	},
	[CHARACTERS.Ganyu]: {
		displayName: "Ganyu",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Ganyu",
		index: 27,
	},
	[CHARACTERS.Gorou]: {
		displayName: "Gorou",
		element: ELEMENTS.geo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Gorou",
		index: 43,
	},
	[CHARACTERS.HuTao]: {
		displayName: "Hu Tao",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "HuTao",
		index: 28,
	},
	[CHARACTERS.Jean]: {
		displayName: "Jean",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Jean",
		index: 7,
	},
	[CHARACTERS.KaedeharaKazuha]: {
		displayName: "Kazuha",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "KaedeharaKazuha",
		index: 33,
	},
	[CHARACTERS.Kaeya]: {
		displayName: "Kaeya",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Kaeya",
		index: 8,
	},
	[CHARACTERS.KamisatoAyaka]: {
		displayName: "Ayaka",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "KamisatoAyaka",
		index: 34,
	},
	[CHARACTERS.KamisatoAyato]: {
		displayName: "Ayato",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "KamisatoAyato",
		index: 47,
	},
	[CHARACTERS.Kaveh]: {
		displayName: "Kaveh",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Kaveh",
		index: 66,
	},
	[CHARACTERS.Keqing]: {
		displayName: "Keqing",
		element: ELEMENTS.electro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Keqing",
		index: 9,
	},
	[CHARACTERS.Kirara]: {
		displayName: "Kirara",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Kirara",
		index: 67,
	},
	[CHARACTERS.Klee]: {
		displayName: "Klee",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Klee",
		index: 10,
	},
	[CHARACTERS.KujouSara]: {
		displayName: "Sara",
		element: ELEMENTS.electro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "KujouSara",
		index: 38,
	},
	[CHARACTERS.KukiShinobu]: {
		displayName: "Shinobu",
		element: ELEMENTS.electro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "KukiShinobu",
		index: 48,
	},
	[CHARACTERS.Layla]: {
		displayName: "Layla",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Layla",
		index: 57,
	},
	[CHARACTERS.Lisa]: {
		displayName: "Lisa",
		element: ELEMENTS.electro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Lisa",
		index: 11,
	},
	[CHARACTERS.Lynette]: {
		displayName: "Lynette",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Lynette",
		index: 69,
	},
	[CHARACTERS.Lyney]: {
		displayName: "Lyney",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Lyney",
		index: 70,
	},
	[CHARACTERS.Mika]: {
		displayName: "Mika",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Mika",
		index: 64,
	},
	[CHARACTERS.Mona]: {
		displayName: "Mona",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Mona",
		index: 12,
	},
	[CHARACTERS.Nahida]: {
		displayName: "Nahida",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Nahida",
		index: 58,
	},
	[CHARACTERS.Navia]: {
		displayName: "Navia",
		element: ELEMENTS.geo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "Navia",
		index: 76,
	},
	[CHARACTERS.Neuvillette]: {
		displayName: "Neuvillette",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Neuvillette",
		index: 71,
	},
	[CHARACTERS.Nilou]: {
		displayName: "Nilou",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Nilou",
		index: 56,
	},
	[CHARACTERS.Ningguang]: {
		displayName: "Ningguang",
		element: ELEMENTS.geo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Ningguang",
		index: 13,
	},
	[CHARACTERS.Noelle]: {
		displayName: "Noelle",
		element: ELEMENTS.geo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Noelle",
		index: 14,
	},
	[CHARACTERS.Qiqi]: {
		displayName: "Qiqi",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Qiqi",
		index: 15,
	},
	[CHARACTERS.RaidenShogun]: {
		displayName: "Raiden",
		element: ELEMENTS.electro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "RaidenShogun",
		index: 39,
	},
	[CHARACTERS.Razor]: {
		displayName: "Razor",
		element: ELEMENTS.electro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Razor",
		index: 16,
	},
	[CHARACTERS.Rosaria]: {
		displayName: "Rosaria",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Rosaria",
		index: 30,
	},
	[CHARACTERS.SangonomiyaKokomi]: {
		displayName: "Kokomi",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "SangonomiyaKokomi",
		index: 40,
	},
	[CHARACTERS.Sayu]: {
		displayName: "Sayu",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Sayu",
		index: 35,
	},
	[CHARACTERS.Sethos]: {
		displayName: "Sethos",
		element: ELEMENTS.electro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Sethos",
		index: 82,
	},
	[CHARACTERS.Shenhe]: {
		displayName: "Shenhe",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Shenhe",
		index: 44,
	},
	[CHARACTERS.ShikanoinHeizou]: {
		displayName: "Heizou",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "ShikanoinHeizou",
		index: 50,
	},
	[CHARACTERS.Sigewinne]: {
		displayName: "Sigewinne",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Sigewinne",
		index: 83,
	},
	[CHARACTERS.Sucrose]: {
		displayName: "Sucrose",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Sucrose",
		index: 17,
	},
	[CHARACTERS.Tartaglia]: {
		displayName: "Tartaglia",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Tartaglia",
		index: 23,
	},
	[CHARACTERS.Thoma]: {
		displayName: "Thoma",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Thoma",
		index: 41,
	},
	[CHARACTERS.Tighnari]: {
		displayName: "Tighnari",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Tighnari",
		index: 53,
	},
	[CHARACTERS.Traveler]: {
		displayName: "Traveler",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Traveler",
		index: 18,
	},
	[CHARACTERS.Venti]: {
		displayName: "Venti",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Venti",
		index: 19,
	},
	[CHARACTERS.Wanderer]: {
		displayName: "Wanderer",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Wanderer",
		index: 60,
	},
	[CHARACTERS.Wriothesley]: {
		displayName: "Wriothesley",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Wriothesley",
		index: 72,
	},
	[CHARACTERS.Xiangling]: {
		displayName: "Xiangling",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Xiangling",
		index: 20,
	},
	[CHARACTERS.Xianyun]: {
		displayName: "Xianyun",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Xianyun",
		index: 78,
	},
	[CHARACTERS.Xiao]: {
		displayName: "Xiao",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Xiao",
		index: 29,
	},
	[CHARACTERS.Xingqiu]: {
		displayName: "Xingqiu",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Xingqiu",
		index: 21,
	},
	[CHARACTERS.Xinyan]: {
		displayName: "Xinyan",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Xinyan",
		index: 24,
	},
	[CHARACTERS.YaeMiko]: {
		displayName: "Yae Miko",
		element: ELEMENTS.electro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "YaeMiko",
		index: 46,
	},
	[CHARACTERS.Yanfei]: {
		displayName: "Yanfei",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Yanfei",
		index: 32,
	},
	[CHARACTERS.Yaoyao]: {
		displayName: "Yaoyao",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Yaoyao",
		index: 62,
	},
	[CHARACTERS.Yelan]: {
		displayName: "Yelan",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Yelan",
		index: 49,
	},
	[CHARACTERS.Yoimiya]: {
		displayName: "Yoimiya",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Yoimiya",
		index: 36,
	},
	[CHARACTERS.YunJin]: {
		displayName: "Yun Jin",
		element: ELEMENTS.geo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "YunJin",
		index: 45,
	},
	[CHARACTERS.Zhongli]: {
		displayName: "Zhongli",
		element: ELEMENTS.geo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Zhongli",
		index: 25,
	},
};
