/**
 * Extends from names.tsx by associating to CHARACTERS enum to relevant data.
 */

import { ELEMENTS } from "../elements";
import { GenericDetails } from "../generic";
import { RARITY } from "../rarity";
import { WEAPONS } from "../weapons";
import { CHARACTERS } from "./names";

type CharacterMap = {
	[index in CHARACTERS]: CharacterDetail;
};

interface CharacterDetail extends GenericDetails {
	element: ELEMENTS;
	weapon: WEAPONS;
	rarity: RARITY;
}

export const CHARACTER_INFO: CharacterMap = {
	[CHARACTERS.Albedo]: {
		displayName: "Albedo",
		element: ELEMENTS.geo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Albedo",
	},
	[CHARACTERS.Alhaitham]: {
		displayName: "Alhaitham",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Alhaitham",
	},
	[CHARACTERS.Aloy]: {
		displayName: "Aloy",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Aloy",
	},
	[CHARACTERS.Amber]: {
		displayName: "Amber",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Amber",
	},
	[CHARACTERS.AratakiItto]: {
		displayName: "Arataki Itto",
		element: ELEMENTS.geo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "AratakiItto",
	},
	[CHARACTERS.Arlecchino]: {
		displayName: "Arlecchino",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Arlecchino",
	},
	[CHARACTERS.Baizhu]: {
		displayName: "Baizhu",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Baizhu",
	},
	[CHARACTERS.Barbara]: {
		displayName: "Barbara",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Barbara",
	},
	[CHARACTERS.Beidou]: {
		displayName: "Beidou",
		element: ELEMENTS.electro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Beidou",
	},
	[CHARACTERS.Bennett]: {
		displayName: "Bennett",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Bennett",
	},
	[CHARACTERS.Candace]: {
		displayName: "Candace",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Candace",
	},
	[CHARACTERS.Charlotte]: {
		displayName: "Charlotte",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Charlotte",
	},
	[CHARACTERS.Chevreuse]: {
		displayName: "Chevreuse",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Chevreuse",
	},
	[CHARACTERS.Chiori]: {
		displayName: "Chiori",
		element: ELEMENTS.geo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Chiori",
	},
	[CHARACTERS.Chongyun]: {
		displayName: "Chongyun",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Chongyun",
	},
	[CHARACTERS.Clorinde]: {
		displayName: "Clorinde",
		element: ELEMENTS.electro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Clorinde",
	},
	[CHARACTERS.Collei]: {
		displayName: "Collei",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Collei",
	},
	[CHARACTERS.Cyno]: {
		displayName: "Cyno",
		element: ELEMENTS.electro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Cyno",
	},
	[CHARACTERS.Dehya]: {
		displayName: "Dehya",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "Dehya",
	},
	[CHARACTERS.Diluc]: {
		displayName: "Diluc",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "Diluc",
	},
	[CHARACTERS.Diona]: {
		displayName: "Diona",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Diona",
	},
	[CHARACTERS.Dori]: {
		displayName: "Dori",
		element: ELEMENTS.electro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Dori",
	},
	[CHARACTERS.Eula]: {
		displayName: "Eula",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FiveStar,
		imageFileName: "Eula",
	},
	[CHARACTERS.Faruzan]: {
		displayName: "Faruzan",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Faruzan",
	},
	[CHARACTERS.Freminet]: {
		displayName: "Freminet",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Freminet",
	},
	[CHARACTERS.Furina]: {
		displayName: "Furina",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Furina",
	},
	[CHARACTERS.Gaming]: {
		displayName: "Gaming",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Gaming",
	},
	[CHARACTERS.Ganyu]: {
		displayName: "Ganyu",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Ganyu",
	},
	[CHARACTERS.Gorou]: {
		displayName: "Gorou",
		element: ELEMENTS.geo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Gorou",
	},
	[CHARACTERS.HuTao]: {
		displayName: "Hu Tao",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "HuTao",
	},
	[CHARACTERS.Jean]: {
		displayName: "Jean",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Jean",
	},
	[CHARACTERS.KaedeharaKazuha]: {
		displayName: "Kaedehara Kazuha",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "KaedeharaKazuha",
	},
	[CHARACTERS.Kaeya]: {
		displayName: "Kaeya",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Kaeya",
	},
	[CHARACTERS.KamisatoAyaka]: {
		displayName: "Kamisato Ayaka",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "KamisatoAyaka",
	},
	[CHARACTERS.KamisatoAyato]: {
		displayName: "Kamisato Ayato",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "KamisatoAyato",
	},
	[CHARACTERS.Kaveh]: {
		displayName: "Kaveh",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Kaveh",
	},
	[CHARACTERS.Keqing]: {
		displayName: "Keqing",
		element: ELEMENTS.electro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Keqing",
	},
	[CHARACTERS.Kirara]: {
		displayName: "Kirara",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Kirara",
	},
	[CHARACTERS.Klee]: {
		displayName: "Klee",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Klee",
	},
	[CHARACTERS.KujouSara]: {
		displayName: "Kujou Sara",
		element: ELEMENTS.electro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "KujouSara",
	},
	[CHARACTERS.KukiShinobu]: {
		displayName: "Kuki Shinobu",
		element: ELEMENTS.electro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "KukiShinobu",
	},
	[CHARACTERS.Layla]: {
		displayName: "Layla",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Layla",
	},
	[CHARACTERS.Lisa]: {
		displayName: "Lisa",
		element: ELEMENTS.electro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Lisa",
	},
	[CHARACTERS.Lyney]: {
		displayName: "Lyney",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Lyney",
	},
	[CHARACTERS.Mika]: {
		displayName: "Mika",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Mika",
	},
	[CHARACTERS.Mona]: {
		displayName: "Mona",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Mona",
	},
	[CHARACTERS.Nahida]: {
		displayName: "Nahida",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Nahida",
	},
	[CHARACTERS.Neuvillette]: {
		displayName: "Neuvillette",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Neuvillette",
	},
	[CHARACTERS.Nilou]: {
		displayName: "Nilou",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Nilou",
	},
	[CHARACTERS.Ningguang]: {
		displayName: "Ningguang",
		element: ELEMENTS.geo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Ningguang",
	},
	[CHARACTERS.Noelle]: {
		displayName: "Noelle",
		element: ELEMENTS.geo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Noelle",
	},
	[CHARACTERS.Qiqi]: {
		displayName: "Qiqi",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Qiqi",
	},
	[CHARACTERS.RaidenShogun]: {
		displayName: "Raiden Shogun",
		element: ELEMENTS.electro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "RaidenShogun",
	},
	[CHARACTERS.Razor]: {
		displayName: "Razor",
		element: ELEMENTS.electro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Razor",
	},
	[CHARACTERS.Rosaria]: {
		displayName: "Rosaria",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Rosaria",
	},
	[CHARACTERS.SangonomiyaKokomi]: {
		displayName: "Sangonomiya Kokomi",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "SangonomiyaKokomi",
	},
	[CHARACTERS.Sayu]: {
		displayName: "Sayu",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Sayu",
	},
	[CHARACTERS.Sethos]: {
		displayName: "Sethos",
		element: ELEMENTS.electro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FourStar,
		imageFileName: "Sethos",
	},
	[CHARACTERS.Shenhe]: {
		displayName: "Shenhe",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Shenhe",
	},
	[CHARACTERS.ShikanoinHeizou]: {
		displayName: "Shikanoin Heizou",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "ShikanoinHeizou",
	},
	[CHARACTERS.Sigewinne]: {
		displayName: "Sigewinne",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Sigewinne",
	},
	[CHARACTERS.Sucrose]: {
		displayName: "Sucrose",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Sucrose",
	},
	[CHARACTERS.Tartaglia]: {
		displayName: "Tartaglia",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Tartaglia",
	},
	[CHARACTERS.Thoma]: {
		displayName: "Thoma",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Thoma",
	},
	[CHARACTERS.Tighnari]: {
		displayName: "Tighnari",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Tighnari",
	},
	[CHARACTERS.Traveler]: {
		displayName: "Traveler",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.sword,
		rarity: RARITY.FiveStar,
		imageFileName: "Traveler",
	},
	[CHARACTERS.Venti]: {
		displayName: "Venti",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Venti",
	},
	[CHARACTERS.Wanderer]: {
		displayName: "Wanderer",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Wanderer",
	},
	[CHARACTERS.Wriothesley]: {
		displayName: "Wriothesley",
		element: ELEMENTS.cryo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Wriothesley",
	},
	[CHARACTERS.Xiangling]: {
		displayName: "Xiangling",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Xiangling",
	},
	[CHARACTERS.Xianyun]: {
		displayName: "Xianyun",
		element: ELEMENTS.anemo,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FiveStar,
		imageFileName: "Xianyun",
	},
	[CHARACTERS.Xingqiu]: {
		displayName: "Xingqiu",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.sword,
		rarity: RARITY.FourStar,
		imageFileName: "Xingqiu",
	},
	[CHARACTERS.Xinyan]: {
		displayName: "Xinyan",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.claymore,
		rarity: RARITY.FourStar,
		imageFileName: "Xinyan",
	},
	[CHARACTERS.Yanfei]: {
		displayName: "Yanfei",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.catalyst,
		rarity: RARITY.FourStar,
		imageFileName: "Yanfei",
	},
	[CHARACTERS.Yaoyao]: {
		displayName: "Yaoyao",
		element: ELEMENTS.dendro,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "Yaoyao",
	},
	[CHARACTERS.Yelan]: {
		displayName: "Yelan",
		element: ELEMENTS.hydro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Yelan",
	},
	[CHARACTERS.Yoimiya]: {
		displayName: "Yoimiya",
		element: ELEMENTS.pyro,
		weapon: WEAPONS.bow,
		rarity: RARITY.FiveStar,
		imageFileName: "Yoimiya",
	},
	[CHARACTERS.YunJin]: {
		displayName: "Yun Jin",
		element: ELEMENTS.geo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FourStar,
		imageFileName: "YunJin",
	},
	[CHARACTERS.Zhongli]: {
		displayName: "Zhongli",
		element: ELEMENTS.geo,
		weapon: WEAPONS.polearm,
		rarity: RARITY.FiveStar,
		imageFileName: "Zhongli",
	},
};
