import { ELEMENTS } from "../elements";
import { GenericDetails } from "../generic";
import { BOSS_TYPE } from "../level";
import { BOSSES } from "./names";

type BossMap = {
    [index in BOSSES]: BossInfo
}

interface BossInfo extends GenericDetails {
    element: ELEMENTS;
    type: BOSS_TYPE;
    index: Number;
}
// index is the way the server communicates to determine what boss to place on the screen

export const BOSS_DETAIL: BossMap = {
	[BOSSES.AeonblightDrake]: {
		displayName: "Drake",
		element: ELEMENTS.physical,
		type: BOSS_TYPE.Standard,
		imageFileName: "AeonblightDrake",
		onlineFilePath: "https://thumbs4.imagebam.com/57/d8/ce/METS4WA_t.png",
		index: 20,
	},
	[BOSSES.AnemoCube]: {
		displayName: "AnemoCube",
		element: ELEMENTS.anemo,
		type: BOSS_TYPE.Standard,
		imageFileName: "AnemoCube",
		onlineFilePath: "https://thumbs4.imagebam.com/8d/60/99/METS4UO_t.png",
		index: 1,
	},
	[BOSSES.ASIMON]: {
		displayName: "ASIMON",
		element: ELEMENTS.physical,
		type: BOSS_TYPE.Standard,
		imageFileName: "ASIMON",
		onlineFilePath: "https://thumbs4.imagebam.com/01/74/0b/METS4W8_t.png",
		index: 21,
	},
	[BOSSES.IniquitousBaptist]: {
		displayName: "Baptist",
		element: ELEMENTS.physical,
		type: BOSS_TYPE.Standard,
		imageFileName: "Baptist",
        onlineFilePath: "https://thumbs4.imagebam.com/e5/25/79/METS4W1_t.png",
		index: 25,
	},
	[BOSSES.Coppelia]: {
		displayName: "Coppelia",
		element: ELEMENTS.cryo,
		type: BOSS_TYPE.Standard,
		imageFileName: "Coppelia",
		onlineFilePath: "https://thumbs4.imagebam.com/2e/5e/7f/MEUJQHM_t.png",
		index: 26,
	},
	[BOSSES.Coppelius]: {
		displayName: "Coppelius",
		element: ELEMENTS.anemo,
		type: BOSS_TYPE.Standard,
		imageFileName: "Coppelius",
		onlineFilePath: "https://thumbs4.imagebam.com/26/cb/e0/MEUJQIH_t.png",
		index: 27,
	},
	[BOSSES.CryoCube]: {
		displayName: "Cryo Cube",
		element: ELEMENTS.cryo,
		type: BOSS_TYPE.Standard,
		imageFileName: "CryoCube",
		onlineFilePath: "https://thumbs4.imagebam.com/a4/71/4e/METS4UT_t.png",
		index: 9,
	},
	[BOSSES.CryoVine]: {
		displayName: "Cryo Vine",
		element: ELEMENTS.cryo,
		type: BOSS_TYPE.Standard,
		imageFileName: "CryoVine",
		onlineFilePath: "https://thumbs4.imagebam.com/03/04/8a/METS4US_t.png",
		index: 2,
	},
	[BOSSES.DendroCube]: {
		displayName: "Dendro Cube",
		element: ELEMENTS.dendro,
		type: BOSS_TYPE.Standard,
		imageFileName: "DendroCube",
		onlineFilePath: "https://thumbs4.imagebam.com/51/a6/69/METS4W6_t.png",
		index: 22,
	},
	[BOSSES.ElectroCube]: {
		displayName: "Electro Cube",
		element: ELEMENTS.electro,
		type: BOSS_TYPE.Standard,
		imageFileName: "ElectroCube",
		onlineFilePath: "https://thumbs4.imagebam.com/b6/89/8a/METS4UM_t.png",
		index: 3,
	},
	[BOSSES.ElectroVine]: {
		displayName: "Electro Vine",
		element: ELEMENTS.electro,
		type: BOSS_TYPE.Standard,
		imageFileName: "ElectroVine",
		onlineFilePath: "https://thumbs4.imagebam.com/75/72/7b/METS4WC_t.png",
		index: 18,
	},
	[BOSSES.EnkaVishaps]: {
		displayName: "Enka Vishaps",
		element: ELEMENTS.electro,
		type: BOSS_TYPE.Standard,
		imageFileName: "EnkaVishaps",
		onlineFilePath: "https://thumbs4.imagebam.com/2d/68/26/METS4WG_t.png",
		index: 16,
	},
	[BOSSES.ExperimentalFieldGenerator]: {
		displayName: "EFG",
		element: ELEMENTS.geo,
		type: BOSS_TYPE.Standard,
		imageFileName: "EFG",
		onlineFilePath: "https://thumbs2.imgbox.com/83/ea/v9eEVHNx_t.png",
		index: 30,
	},
	[BOSSES.GeoCube]: {
		displayName: "Geo Cube",
		element: ELEMENTS.geo,
		type: BOSS_TYPE.Standard,
		imageFileName: "GeoCube",
        onlineFilePath: "https://thumbs4.imagebam.com/3c/2b/c6/METS4UU_t.png",
		index: 4,
	},
	[BOSSES.GoldenWolflord]: {
		displayName: "Wolflord",
		element: ELEMENTS.geo,
		type: BOSS_TYPE.Standard,
		imageFileName: "Wolflord",
        onlineFilePath: "https://thumbs4.imagebam.com/3e/4b/8b/METS4VK_t.png",
		index: 15,
	},
	[BOSSES.HydroCube]: {
		displayName: "HydroCube",
		element: ELEMENTS.hydro,
		type: BOSS_TYPE.Standard,
		imageFileName: "HydroCube",
        onlineFilePath: "https://images4.imagebam.com/84/5b/8e/METS4VH_o.png",
		index: 13,
	},
	[BOSSES.HydroTulpa]: {
		displayName: "Tulpa",
		element: ELEMENTS.hydro,
		type: BOSS_TYPE.Standard,
		imageFileName: "HydroTulpa",
        onlineFilePath: "https://thumbs4.imagebam.com/1d/15/89/METS4VP_t.png",
		index: 33,
	},
	[BOSSES.JadeplumeTerrorshroom]: {
		displayName: "Terrorshroom",
		element: ELEMENTS.dendro,
		type: BOSS_TYPE.Standard,
		imageFileName: "JadeplumeTerrorshroom",
        onlineFilePath: "https://thumbs4.imagebam.com/f4/e7/b7/METS4WF_t.png",
		index: 19,
	},
	[BOSSES.LegatusGolem]: {
		displayName: "Golem",
		element: ELEMENTS.pyro,
		type: BOSS_TYPE.Standard,
		imageFileName: "LegatusGolem",
		onlineFilePath: "https://thumbs2.imgbox.com/0a/27/vN4b4URe_t.png",
		index: 38,
	},
	[BOSSES.MaguuKenki]: {
		displayName: "Kenki",
		element: ELEMENTS.anemo,
		type: BOSS_TYPE.Standard,
		imageFileName: "MaguuKenki",
		onlineFilePath: "https://thumbs4.imagebam.com/66/98/db/METS4V8_t.png",
		index: 10,
	},
	[BOSSES.MountainKing]: {
		displayName: "Mountain King",
		element: ELEMENTS.dendro,
		type: BOSS_TYPE.Standard,
		imageFileName: "MountainKing",
		onlineFilePath: "https://thumbs4.imagebam.com/1e/de/c7/MEVO2LF_t.png",
		index: 39
	},
	[BOSSES.Oceanid]: {
		displayName: "Oceanid",
		element: ELEMENTS.anemo,
		type: BOSS_TYPE.Standard,
		imageFileName: "Oceanid",
		onlineFilePath: "https://thumbs4.imagebam.com/cd/58/d7/METS4UY_t.png",
		index: 5,
	},
	[BOSSES.PMA]: {
		displayName: "PMA",
		element: ELEMENTS.physical,
		type: BOSS_TYPE.Standard,
		imageFileName: "PMA",
		onlineFilePath: "https://images4.imagebam.com/65/66/44/METS4VB_o.png",
		index: 11,
	},
	[BOSSES.PrimoVishap]: {
		displayName: "Primovishap",
		element: ELEMENTS.geo,
		type: BOSS_TYPE.Standard,
		imageFileName: "Primovishap",
		onlineFilePath: "https://thumbs4.imagebam.com/23/40/04/METS4V2_t.png",
		index: 7,
	},
	[BOSSES.PyroCrab]: {
		displayName: "Pyro Crab",
		element: ELEMENTS.pyro,
		type: BOSS_TYPE.Standard,
		imageFileName: "PyroCrab",
		onlineFilePath: "https://thumbs4.imagebam.com/e6/cd/11/METS4VU_t.png",
		index: 28,
	},
	[BOSSES.PyroCube]: {
		displayName: "Pyro Cube",
		element: ELEMENTS.pyro,
		type: BOSS_TYPE.Standard,
		imageFileName: "PyroCube",
		onlineFilePath: "https://images4.imagebam.com/a6/e6/69/METS4VF_o.png",
		index: 12,
	},
	[BOSSES.PyroVine]: {
		displayName: "Pyro Vine",
		element: ELEMENTS.pyro,
		type: BOSS_TYPE.Standard,
		imageFileName: "PyroVine",
		onlineFilePath: "https://thumbs4.imagebam.com/a7/bc/c2/METS4UW_t.png",
		index: 6,
	},
	[BOSSES.Ququsaur]: {
		displayName: "Goldflame",
		element: ELEMENTS.pyro,
		type: BOSS_TYPE.Standard,
		imageFileName: "Ququsaur",
		onlineFilePath: "https://thumbs4.imagebam.com/38/76/4d/MEVO2OM_t.png",
		index: 40,
	},
	[BOSSES.RuinSerpent]: {
		displayName: "Serpent",
		element: ELEMENTS.physical,
		type: BOSS_TYPE.Standard,
		imageFileName: "RuinSerpent",
		onlineFilePath: "https://thumbs4.imagebam.com/39/a0/48/METS4V4_t.png",
		index: 17,
	},
	[BOSSES.MillenialPearlSeahorse]: {
		displayName: "Seahorse",
		element: ELEMENTS.electro,
		type: BOSS_TYPE.Standard,
		imageFileName: "Seahorse",
		onlineFilePath: "https://thumbs4.imagebam.com/19/9e/b3/METS4VT_t.png",
		index: 31,
	},
	[BOSSES.SolitarySuanii]: {
		displayName: "Suanni",
		element: ELEMENTS.hydro,
		type: BOSS_TYPE.Standard,
		imageFileName: "Suanni",
		onlineFilePath: "https://thumbs4.imagebam.com/66/f5/88/METS4V6_t.png",
		index: 35,
	},
	[BOSSES.Thunderbird]: {
		displayName: "Thunderbird",
		element: ELEMENTS.electro,
		type: BOSS_TYPE.Standard,
		imageFileName: "Thunderbird",
		onlineFilePath: "https://thumbs4.imagebam.com/2a/b1/95/METS4VJ_t.png",
		index: 14,
	},
	[BOSSES.Wenut]: {
		displayName: "Wenut",
		element: ELEMENTS.anemo,
		type: BOSS_TYPE.Standard,
		imageFileName: "Wenut",
		onlineFilePath: "https://thumbs4.imagebam.com/16/64/60/METS4W4_t.png",
		index: 23,
	},
	[BOSSES.Apep]: {
		displayName: "Apep",
		element: ELEMENTS.dendro,
		type: BOSS_TYPE.Weekly,
		imageFileName: "Apep",
		onlineFilePath: "https://thumbs4.imagebam.com/75/7a/be/METS4UF_t.png",
		index: 24,
	},
	[BOSSES.Azhdaha]: {
		displayName: "Azhdaha",
		element: ELEMENTS.geo,
		type: BOSS_TYPE.Weekly,
		imageFileName: "Azhdaha",
		onlineFilePath: "https://thumbs4.imagebam.com/48/f5/54/METS4U7_t.png",
		index: 8,
	},
	[BOSSES.Knave]: {
		displayName: "Knave",
		element: ELEMENTS.pyro,
		type: BOSS_TYPE.Weekly,
		imageFileName: "Knave",
		onlineFilePath: "https://thumbs4.imagebam.com/6a/fd/eb/METS4UB_t.png",
		index: 37,
	},
	[BOSSES.Narwhal]: {
		displayName: "Narwhal",
		element: ELEMENTS.hydro,
		type: BOSS_TYPE.Weekly,
		imageFileName: "Narwhal",
		onlineFilePath: "https://thumbs4.imagebam.com/44/33/67/METS4UD_t.png",
		index: 32,
	},
	[BOSSES.ArrayMek]: {
		displayName: "Array Mek",
		element: ELEMENTS.geo,
		type: BOSS_TYPE.Legend,
		imageFileName: "ArrayMek",
		onlineFilePath: "https://thumbs4.imagebam.com/f6/0e/0e/METS4UH_t.png",
		index: 29,
	},
	[BOSSES.ChizangVishaps]: {
		displayName: "Chizang Vishaps",
		element: ELEMENTS.geo,
		type: BOSS_TYPE.Legend,
		imageFileName: "ChizangVishaps",
		onlineFilePath: "https://thumbs4.imagebam.com/b9/46/85/METS4UI_t.png",
		index: 34,
	},
	[BOSSES.Cineas]: {
		displayName: "Cineas",
		element: ELEMENTS.hydro,
		type: BOSS_TYPE.Legend,
		imageFileName: "Cineas",
		onlineFilePath: "https://thumbs4.imagebam.com/f1/9f/75/METS4UK_t.png",
		index: 36,
	},
};