// This is just names. Background colors will depend on boss type - local legends have one color, weeklies another and normal bosses a third.
export enum BOSSES {
    AnemoCube="AnemoCube",
    CryoVine="CryoVine",
    ElectroCube="ElectroCube",
    PyroVine="PyroVine",
    GeoCube="GeoCube",
    Oceanid="Oceanid",
    PrimoVishap="PrimoVishap",
    CryoCube = "CryoCube",
    MaguuKenki="MaguuKenki",
    PMA="PMA",
    PyroCube="PyroCube",
    HydroCube="HydroCube",
    Thunderbird="Thunderbird",
    GoldenWolflord="GoldenWolflord",
    EnkaVishaps="EnkaVishaps",
    RuinSerpent="RuinSerpent",
    ElectroVine="ElectroVine",
    JadeplumeTerrorshroom="JadeplumeTerrorshroom",
    AeonblightDrake="AeonblightDrake",
    ASIMON="ASIMON",
    DendroCube="DendroCube",
    Wenut="Wenut",
    IniquitousBaptist="IniquitousBaptist",
    Coppelia="Coppelia",
    Coppelius="Coppelius",
    PyroCrab="PyroCrab",
    ExperimentalFieldGenerator="ExperimentalFieldGenerator",
    MillenialPearlSeahorse="MillenialPearlSeahorse",
    HydroTulpa="HydroTulpa",
    SolitarySuanii="SolitarySuanni",
    LegatusGolem="LegatusGolem",
    MountainKing="MountainKing",
    Ququsaur="Ququsaur",
    Automoton="Automoton",
    // new boss

    Azhdaha="Azhdaha",
    Apep="Apep",
    Narwhal="Narwhal",
    Knave="Knave",

    ArrayMek="ArrayMek",
    ChizangVishaps="ChizangVishaps",
    Cineas="Cineas"
}