// This is just names. Background colors will depend on boss type - local legends have one color, weeklies another and normal bosses a third.
export enum BOSSES {
	Random = "Random",
	None = "None",
	AnemoCube = "AnemoCube",
	CryoVine = "CryoVine",
	ElectroCube = "ElectroCube",
	GeoCube = "GeoCube",
	// Oceanid = "Oceanid",
	PyroVine = "PyroVine",
	PrimoVishap = "PrimoVishap",
	CryoCube = "CryoCube",
	MaguuKenki = "MaguuKenki",
	PMA = "PMA",
	PyroCube = "PyroCube",
	HydroCube = "HydroCube",
	Thunderbird = "Thunderbird",
	// GoldenWolflord = "GoldenWolflord",
	EnkaVishaps = "EnkaVishaps",
	RuinSerpent = "RuinSerpent",
	ElectroVine = "ElectroVine",
	JadeplumeTerrorshroom = "JadeplumeTerrorshroom",
	AeonblightDrake = "AeonblightDrake",
	ASIMON = "ASIMON",
	DendroCube = "DendroCube",
	Wenut = "Wenut",
	IniquitousBaptist = "IniquitousBaptist",
	Coppelia = "Coppelia",
	Coppelius = "Coppelius",
	PyroCrab = "PyroCrab",
	EFG = "EFG",
	MillenialPearlSeahorse = "MillenialPearlSeahorse",
	HydroTulpa = "HydroTulpa",
	SolitarySuanni = "SolitarySuanni",
	LegatusGolem = "LegatusGolem",
	Goldflame = "Goldflame",
	MountainKing = "MountainKing",
	Automaton = "Automaton",
	Papilla = "Papilla",
	Spiritspeaker = "Spiritspeaker",
    LavaDragon = "LavaDragon",
	Overseer = "Overseer",
	KnuckleDuckle = "KnuckleDuckle",
	Moonfly = "Moonfly",
	

	// Azhdaha = "Azhdaha",
	Apep = "Apep",
	Narwhal = "Narwhal",
	Knave = "Knave",
	ErodedLord = "ErodedLord",
	ChessGame = "ChessGame",

	// 4.0
	Vivianne = "Vivianne",
	// 4.1
	ArrayMek = "ArrayMek",
	// 4.2
	Deianeira = "Deianeira",
	Rocky = "Rocky",
	// 4.4
	ChizhangVishaps = "ChizhangVishaps",
	// 4.6
	Cineas = "Cineas",
	// 5.0
	Balachko = "Balachko",
	Cocijo = "Cocijo",
	Polychrome = "Polychrome",
	// 5.2
	Bronzelock = "Bronzelock",
}